import { Inter, Open_Sans } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/common/Sidebar";
import ViewChangerProvider from "@/providers/ViewChangerProvider";

const openSans = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewChangerProvider>
      <html lang="en">
        <body
          className={`${openSans.className} w-screen h-screen flex justify-between p-6 space-x-6`}
        >
          <Sidebar />
          <div className="w-4/5">{children}</div>
        </body>
      </html>
    </ViewChangerProvider>
  );
}
